### ISSUE TITLE
.env

### ISSUE THREAD

**Issue by Notendoos** [WesselSmit/progressive-web-apps-1920#3]
Aangezien je nu met een node server werkt is het beter om deze ook in een `.env` te zetten.
https://github.com/WesselSmit/progressive-web-apps-1920/blob/340fa7f7bff4d1421e585a089253f81b48c4f4f7/modules/api.js#L9

Ik namelijk wel dat je daar al gebruik van maakt.
https://github.com/WesselSmit/progressive-web-apps-1920/blob/340fa7f7bff4d1421e585a089253f81b48c4f4f7/index.js#L1

**Comment by WesselSmit** [comment]
done, thanks voor de tip
